#!/usr/bin/env python3
"""
plant — generated by dynamicalnodes.ROSNode.write_ROSNode_to_rclpy().

Run:
    python3 plant_node.py
"""

# ──────────────────────────────────────────────────────────────────────
# Imports
# ──────────────────────────────────────────────────────────────────────

from collections import deque
import numpy as np

import rclpy
from rclpy.node import Node
from rclpy.executors import SingleThreadedExecutor
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.qos import QoSProfile, QoSHistoryPolicy, QoSReliabilityPolicy

from std_msgs.msg import Float64

from dynamicalnodes import DynamicalSystem
from dynamicalnodes.ros2py_py2ros import ros2py_float64, py2ros_float64


# ──────────────────────────────────────────────────────────────────────
# Functions — inlined from source
# ──────────────────────────────────────────────────────────────────────

def fcar(xk, uk, m, b, dt):
    v = xk
    return v + dt * (uk - b * v) / m


def hcar(xk, sigma=0.0):
    v = xk
    return np.abs(v) + np.random.normal(0.0, sigma)


# ──────────────────────────────────────────────────────────────────────
# QoS — tune history / depth / reliability to match your transport
# ──────────────────────────────────────────────────────────────────────

QOS = QoSProfile(
    history=QoSHistoryPolicy.KEEP_LAST,
    depth=10,
    reliability=QoSReliabilityPolicy.RELIABLE,
)


class PlantNode(Node):

    """
    Subscribes to:
        /uk  (Float64)  →  uk  [ros2py_float64, buffer=1]
    Publishes to:
        /yk  (Float64)  [py2ros_float64]

    step trigger: event-driven (fires on each subscription callback)
    sync_mode='any': step when any subscription receives a fresh value.
    """

    def __init__(self) -> None:
        super().__init__("plant")
        self._cb_group = ReentrantCallbackGroup()

        self._system = DynamicalSystem(f=fcar, h=hcar)
        self._state = 0.0  # initial state
        self._t0 = self.get_clock().now()  # wall-clock reference for 'tk'

        self._static_params: dict = {'m': 1500.0, 'b': 50.0, 'dt': 0.1, 'sigma': np.float64(1.4142135623730951)}  # static params

        # ── Subscription buffers ───────────────────────────────────────────────
        self._uk_buf: deque = deque(maxlen=1)

        # ── Subscriptions ────────────────────────────────────────────────────
        self._uk_sub = self.create_subscription(
            Float64, '/uk',
            self._uk_cb, QOS,
            callback_group=self._cb_group,
        )

        # ── Publishers ────────────────────────────────────────────────────────
        self._pub_yk = self.create_publisher(
            Float64, '/yk', QOS,
        )

        self.get_logger().info("plant started")

    # ────────────────────────────────────────────────────────────────────
    # Subscription callbacks
    # ────────────────────────────────────────────────────────────────────
    # Each callback converts the incoming message to NumPy, stores it with an
    # arrival timestamp, then attempts a control step. The (time, value) tuple
    # enables the staleness check in _fresh(). _run_step() proceeds only when
    # sync_mode conditions are satisfied.

    def _uk_cb(self, msg: Float64) -> None:
        arr = np.asarray(ros2py_float64(msg), dtype=float)  # ROS msg → NumPy
        ts = self.get_clock().now().nanoseconds * 1e-9
        self._uk_buf.append((ts, arr))
        self._run_step()

    @staticmethod
    def _fresh(buf: deque, stale_after, now_ts: float):
        """Newest buffered value if its timestamp is within stale_after seconds of now_ts, else None."""
        if not buf:
            return None
        ts, val = buf[-1]
        if stale_after is not None and (now_ts - ts) > stale_after:
            return None
        return val

    # ────────────────────────────────────────────────────────────────────
    # Control step
    # ────────────────────────────────────────────────────────────────────
    # Builds kwargs from static params, dynamic params, fresh subscription
    # values, and current state, then calls DynamicalSystem.eval() and
    # publishes. Skipped entirely when sync_mode conditions are not met.

    def _run_step(self) -> None:
        _now = self.get_clock().now()
        now_ts: float = _now.nanoseconds * 1e-9  # ROS clock, seconds since epoch
        tk: float = (_now - self._t0).nanoseconds * 1e-9  # seconds since node started

        # Gather fresh inputs
        uk = self._fresh(self._uk_buf, None, now_ts)

        # sync_mode='any'
        if uk is None:
            return  # all inputs are stale — skip this tick

        kwargs: dict = {"tk": tk, **self._static_params}
        if uk is not None:
            kwargs["uk"] = uk
        if self._state is not None:
            kwargs["xk"] = self._state

        x_next, yk = self._system.eval(**kwargs)
        if self._system.f is not None:
            self._state = x_next  # stateful: advance to next state

        _arr = np.asarray(yk, dtype=float).ravel()
        msg = py2ros_float64(_arr)
        if hasattr(msg, 'header'):
            msg.header.stamp = self.get_clock().now().to_msg()
        self._pub_yk.publish(msg)


# ──────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────

def main() -> None:
    rclpy.init()
    node = PlantNode()
    executor = SingleThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
