#!/usr/bin/env python3
"""
ann_estimator — generated by dynamicalnodes.ROSNode.write_ROSNode_to_rclpy().

Run:
    python3 ann_estimator_node.py
"""

# ──────────────────────────────────────────────────────────────────────
# Imports
# ──────────────────────────────────────────────────────────────────────

from collections import deque
import numpy as np

import rclpy
from rclpy.node import Node
from rclpy.executors import SingleThreadedExecutor
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.qos import QoSProfile, QoSHistoryPolicy, QoSReliabilityPolicy

from sensor_msgs.msg import Imu, NavSatFix
from std_msgs.msg import Float64MultiArray

from dynamicalnodes import DynamicalSystem
from dynamicalnodes.ros2py_py2ros import ros2py_nav_sat_fix, ros2py_imu, py2ros_float64_multiarray


# ──────────────────────────────────────────────────────────────────────
# Functions — inlined from source
# ──────────────────────────────────────────────────────────────────────

def ann_h(gps, imu, W1, b1, W2, b2):
    inp = np.array([float(gps[0]), float(imu[7])])  # [x_gps, ax_imu]
    return W2 @ np.tanh(W1 @ inp + b1) + b2         # [x_est, vx_est]


# ──────────────────────────────────────────────────────────────────────
# QoS — tune history / depth / reliability to match your transport
# ──────────────────────────────────────────────────────────────────────

QOS = QoSProfile(
    history=QoSHistoryPolicy.KEEP_LAST,
    depth=10,
    reliability=QoSReliabilityPolicy.RELIABLE,
)


class AnnEstimatorNode(Node):

    """
    Subscribes to:
        /gps  (NavSatFix)  →  gps  [ros2py_nav_sat_fix, buffer=5, stale_after=2.0s]
        /imu  (Imu)  →  imu  [ros2py_imu, buffer=20, stale_after=0.02s]
    Publishes to:
        /x_est_ann  (Float64MultiArray)  [py2ros_float64_multiarray]

    step trigger: event-driven (fires on each subscription callback)
    sync_mode='all': step only when every subscription has a fresh value.
    """

    def __init__(self) -> None:
        super().__init__("ann_estimator")
        self._cb_group = ReentrantCallbackGroup()

        self._system = DynamicalSystem(h=ann_h)
        self._state = None  # initial state — set before deploying if stateful
        self._t0 = self.get_clock().now()  # wall-clock reference for 'tk'

        self._static_params: dict = {'W1': np.array([[0.01257302210933933, -0.013210486329130189], [0.06404226504432821, 0.010490011715303971], [-0.0535669373161111, 0.03615950549094848], [0.13040000451301373, 0.09470809631292422], [-0.07037352358069926, -0.12654214710460526], [-0.06232744625373522, 0.00413259793472436], [-0.23250307746388343, -0.021879166393254573], [-0.12459109472530652, -0.07322673547034517]]), 'b1': np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 'W2': np.array([[-0.054425898285730995, -0.031630015636915455, 0.04116305363741329, 0.10425133694426776, -0.012853466294403426, 0.1366463470549686, -0.06651946734866136, 0.035151007009301974], [0.09034701816518087, 0.009401229776087457, -0.07434992493538084, -0.09217253762584195, -0.045772582566733916, 0.022019512347004944, -0.10096181835387359, -0.020917557487171307]]), 'b2': np.array([0.0, 0.0])}  # static params

        # ── Subscription buffers ───────────────────────────────────────────────
        self._gps_buf: deque = deque(maxlen=5)
        self._imu_buf: deque = deque(maxlen=20)

        # ── Subscriptions ────────────────────────────────────────────────────
        self._gps_sub = self.create_subscription(
            NavSatFix, '/gps',
            self._gps_cb, QOS,
            callback_group=self._cb_group,
        )
        self._imu_sub = self.create_subscription(
            Imu, '/imu',
            self._imu_cb, QOS,
            callback_group=self._cb_group,
        )

        # ── Publishers ────────────────────────────────────────────────────────
        self._pub_x_est_ann = self.create_publisher(
            Float64MultiArray, '/x_est_ann', QOS,
        )

        self.get_logger().info("ann_estimator started")

    # ────────────────────────────────────────────────────────────────────
    # Subscription callbacks
    # ────────────────────────────────────────────────────────────────────
    # Each callback converts the incoming message to NumPy, stores it with an
    # arrival timestamp, then attempts a control step. The (time, value) tuple
    # enables the staleness check in _fresh(). _run_step() proceeds only when
    # sync_mode conditions are satisfied.

    def _gps_cb(self, msg: NavSatFix) -> None:
        arr = np.asarray(ros2py_nav_sat_fix(msg), dtype=float)  # ROS msg → NumPy
        ts = self.get_clock().now().nanoseconds * 1e-9
        self._gps_buf.append((ts, arr))
        self._run_step()

    def _imu_cb(self, msg: Imu) -> None:
        arr = np.asarray(ros2py_imu(msg), dtype=float)  # ROS msg → NumPy
        ts = self.get_clock().now().nanoseconds * 1e-9
        self._imu_buf.append((ts, arr))
        self._run_step()

    @staticmethod
    def _fresh(buf: deque, stale_after, now_ts: float):
        """Newest buffered value if its timestamp is within stale_after seconds of now_ts, else None."""
        if not buf:
            return None
        ts, val = buf[-1]
        if stale_after is not None and (now_ts - ts) > stale_after:
            return None
        return val

    # ────────────────────────────────────────────────────────────────────
    # Control step
    # ────────────────────────────────────────────────────────────────────
    # Builds kwargs from static params, dynamic params, fresh subscription
    # values, and current state, then calls DynamicalSystem.step() and
    # publishes. Skipped entirely when sync_mode conditions are not met.

    def _run_step(self) -> None:
        _now = self.get_clock().now()
        now_ts: float = _now.nanoseconds * 1e-9  # ROS clock, seconds since epoch
        tk: float = (_now - self._t0).nanoseconds * 1e-9  # seconds since node started

        # Gather fresh inputs
        gps = self._fresh(self._gps_buf, 2.0, now_ts)
        imu = self._fresh(self._imu_buf, 0.02, now_ts)

        # sync_mode='all'
        if gps is None or imu is None:
            return  # not all inputs are fresh — skip this tick

        kwargs: dict = {"tk": tk, **self._static_params}
        if gps is not None:
            kwargs["gps"] = gps
        if imu is not None:
            kwargs["imu"] = imu

        result = self._system.step(**kwargs)
        if self._system.f is not None:
            self._state, yk = result  # stateful: (next_state, output)
        else:
            yk = result               # stateless: output only

        _arr = np.asarray(yk, dtype=float).ravel()
        msg = py2ros_float64_multiarray(_arr)
        if hasattr(msg, 'header'):
            msg.header.stamp = self.get_clock().now().to_msg()
        self._pub_x_est_ann.publish(msg)


# ──────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────

def main() -> None:
    rclpy.init()
    node = AnnEstimatorNode()
    executor = SingleThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
