#!/usr/bin/env python3
"""
controller — generated by dynamicalnodes.ROSNode.write_ROSNode_to_rclpy().

Run:
    python3 controller_node.py
"""

# ──────────────────────────────────────────────────────────────────────
# Imports
# ──────────────────────────────────────────────────────────────────────

from collections import deque
import numpy as np

import rclpy
from rclpy.node import Node
from rclpy.executors import SingleThreadedExecutor
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.qos import QoSProfile, QoSHistoryPolicy, QoSReliabilityPolicy

from std_msgs.msg import Float64

from dynamicalnodes import DynamicalSystem
from dynamicalnodes.ros2py_py2ros import ros2py_float64, py2ros_float64


# ──────────────────────────────────────────────────────────────────────
# Functions — inlined from source
# ──────────────────────────────────────────────────────────────────────

def pid_f(ck, rk, xhatk, KP, KI, KD, dt):
    """Update PID state: returns (prev_error, integral)."""
    e_prev, e_int = ck
    ek = rk - xhatk
    return (ek, e_int + ek * dt)


def pid_h(ck, rk, xhatk, KP, KI, KD, dt):
    """Compute control output from current PID state."""
    e_prev, e_int = ck
    ek = rk - xhatk
    e_der = (ek - e_prev) / dt
    return KP * ek + KI * e_int + KD * e_der


# ──────────────────────────────────────────────────────────────────────
# QoS — tune history / depth / reliability to match your transport
# ──────────────────────────────────────────────────────────────────────

QOS = QoSProfile(
    history=QoSHistoryPolicy.KEEP_LAST,
    depth=10,
    reliability=QoSReliabilityPolicy.RELIABLE,
)


class ControllerNode(Node):

    """
    Subscribes to:
        /rk  (Float64)  →  rk  [ros2py_float64, buffer=1]
        /xhatk  (Float64)  →  xhatk  [ros2py_float64, buffer=1, initial=0.0]
    Publishes to:
        /uk  (Float64)  [py2ros_float64]

    step trigger: event-driven (fires on each subscription callback)
    sync_mode='all': step only when every subscription has a fresh value.

    Dynamic params (ros2 param set /controller <name> <value>):
        KP: 500.0
        KI: 30.0
        KD: 10.0
    """

    def __init__(self) -> None:
        super().__init__("controller")
        self._cb_group = ReentrantCallbackGroup()

        self._system = DynamicalSystem(f=pid_f, h=pid_h)
        self._state = (0.0, 0.0)  # initial state
        self._t0 = self.get_clock().now()  # wall-clock reference for 'tk'

        self._static_params: dict = {'dt': 0.1}  # static params

        # ── Dynamic params ───────────────────────────────────────────────────
        # Readable/writable at runtime: ros2 param set /controller <name> <value>
        self.declare_parameter('KP', 500.0)
        self.declare_parameter('KI', 30.0)
        self.declare_parameter('KD', 10.0)

        # ── Subscription buffers ───────────────────────────────────────────────
        self._rk_buf: deque = deque(maxlen=1)
        self._xhatk_buf: deque = deque(maxlen=1)

        # ── Subscriptions ────────────────────────────────────────────────────
        self._rk_sub = self.create_subscription(
            Float64, '/rk',
            self._rk_cb, QOS,
            callback_group=self._cb_group,
        )
        self._xhatk_sub = self.create_subscription(
            Float64, '/xhatk',
            self._xhatk_cb, QOS,
            callback_group=self._cb_group,
        )

        # ── Publishers ────────────────────────────────────────────────────────
        self._pub_uk = self.create_publisher(
            Float64, '/uk', QOS,
        )

        self.get_logger().info("controller started")

    # ────────────────────────────────────────────────────────────────────
    # Subscription callbacks
    # ────────────────────────────────────────────────────────────────────
    # Each callback converts the incoming message to NumPy, stores it with an
    # arrival timestamp, then attempts a control step. The (time, value) tuple
    # enables the staleness check in _fresh(). _run_step() proceeds only when
    # sync_mode conditions are satisfied.

    def _rk_cb(self, msg: Float64) -> None:
        arr = np.asarray(ros2py_float64(msg), dtype=float)  # ROS msg → NumPy
        ts = self.get_clock().now().nanoseconds * 1e-9
        self._rk_buf.append((ts, arr))
        self._run_step()

    def _xhatk_cb(self, msg: Float64) -> None:
        arr = np.asarray(ros2py_float64(msg), dtype=float)  # ROS msg → NumPy
        ts = self.get_clock().now().nanoseconds * 1e-9
        self._xhatk_buf.append((ts, arr))
        self._run_step()

    @staticmethod
    def _fresh(buf: deque, stale_after, now_ts: float):
        """Newest buffered value if its timestamp is within stale_after seconds of now_ts, else None."""
        if not buf:
            return None
        ts, val = buf[-1]
        if stale_after is not None and (now_ts - ts) > stale_after:
            return None
        return val

    # ────────────────────────────────────────────────────────────────────
    # Control step
    # ────────────────────────────────────────────────────────────────────
    # Builds kwargs from static params, dynamic params, fresh subscription
    # values, and current state, then calls DynamicalSystem.step() and
    # publishes. Skipped entirely when sync_mode conditions are not met.

    def _run_step(self) -> None:
        _now = self.get_clock().now()
        now_ts: float = _now.nanoseconds * 1e-9  # ROS clock, seconds since epoch
        tk: float = (_now - self._t0).nanoseconds * 1e-9  # seconds since node started

        # Gather fresh inputs
        rk = self._fresh(self._rk_buf, None, now_ts)
        xhatk = self._fresh(self._xhatk_buf, None, now_ts)

        # Cold-start fallbacks — used only before first message arrives
        if xhatk is None and not self._xhatk_buf:
            xhatk = 0.0  # initial input

        # sync_mode='all'
        if rk is None or xhatk is None:
            return  # not all inputs are fresh — skip this tick

        kwargs: dict = {"tk": tk, **self._static_params}
        kwargs["KP"] = self.get_parameter("KP").value
        kwargs["KI"] = self.get_parameter("KI").value
        kwargs["KD"] = self.get_parameter("KD").value
        if rk is not None:
            kwargs["rk"] = rk
        if xhatk is not None:
            kwargs["xhatk"] = xhatk
        if self._state is not None:
            kwargs["ck"] = self._state

        result = self._system.step(**kwargs)
        if self._system.f is not None:
            self._state, yk = result  # stateful: (next_state, output)
        else:
            yk = result               # stateless: output only

        _arr = np.asarray(yk, dtype=float).ravel()
        msg = py2ros_float64(_arr)
        if hasattr(msg, 'header'):
            msg.header.stamp = self.get_clock().now().to_msg()
        self._pub_uk.publish(msg)


# ──────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────

def main() -> None:
    rclpy.init()
    node = ControllerNode()
    executor = SingleThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
