#!/usr/bin/env python3
"""
kf_estimator — generated by dynamicalnodes.ROSNode.write_ROSNode_to_rclpy().

Run:
    python3 kf_estimator_node.py
"""

# ──────────────────────────────────────────────────────────────────────
# Imports
# ──────────────────────────────────────────────────────────────────────

from collections import deque
import numpy as np

import rclpy
from rclpy.node import Node
from rclpy.executors import SingleThreadedExecutor
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.qos import QoSProfile, QoSHistoryPolicy, QoSReliabilityPolicy

from sensor_msgs.msg import Imu, NavSatFix
from std_msgs.msg import Float64

from dynamicalnodes import DynamicalSystem
from dynamicalnodes.ros2py_py2ros import ros2py_nav_sat_fix, ros2py_imu, py2ros_float64


# ──────────────────────────────────────────────────────────────────────
# Functions — inlined from source
# ──────────────────────────────────────────────────────────────────────

def kf_f(zk, imu, Fk, Bk, Hk, Qk, Rk, gps=None):
    """Predict always; update only when GPS is available."""
    x, P = zk
    ax = float(imu[7])                  # linear_acceleration.x is at index 7
    x_pred = Fk @ x + Bk * ax
    P_pred = Fk @ P @ Fk.T + Qk
    if gps is not None:
        y     = np.array([float(gps[0])])  # latitude = x position
        S     = Hk @ P_pred @ Hk.T + Rk
        K     = P_pred @ Hk.T @ np.linalg.inv(S)
        x_upd = x_pred + K @ (y - Hk @ x_pred)
        P_upd = (np.eye(2) - K @ Hk) @ P_pred
    else:
        x_upd, P_upd = x_pred, P_pred
    return (x_upd, P_upd)


def kf_h(zk):
    x, P = zk
    return {"x_est": float(x[0]), "P00": float(P[0, 0])}  # position + position variance


# ──────────────────────────────────────────────────────────────────────
# QoS — tune history / depth / reliability to match your transport
# ──────────────────────────────────────────────────────────────────────

QOS = QoSProfile(
    history=QoSHistoryPolicy.KEEP_LAST,
    depth=10,
    reliability=QoSReliabilityPolicy.RELIABLE,
)


class KfEstimatorNode(Node):

    """
    Subscribes to:
        /gps  (NavSatFix)  →  gps  [ros2py_nav_sat_fix, buffer=5, stale_after=2.0s]
        /imu  (Imu)  →  imu  [ros2py_imu, buffer=20, stale_after=0.02s]
    Publishes to:
        /x_est_kf  (Float64)  [py2ros_float64, key='x_est']
        /P_kf  (Float64)  [py2ros_float64, key='P00']

    step trigger: event-driven (fires on each subscription callback)
    sync_mode='any': step when any subscription receives a fresh value.
    """

    def __init__(self) -> None:
        super().__init__("kf_estimator")
        self._cb_group = ReentrantCallbackGroup()

        self._system = DynamicalSystem(f=kf_f, h=kf_h)
        self._state = (np.array([0.0, 0.0]), np.array([[100.0, 0.0], [0.0, 100.0]]))  # initial state
        self._t0 = self.get_clock().now()  # wall-clock reference for 'tk'

        self._static_params: dict = {'Fk': np.array([[1.0, 0.01], [0.0, 1.0]]), 'Bk': np.array([5e-05, 0.01]), 'Hk': np.array([[1.0, 0.0]]), 'Qk': np.array([[0.0001, 0.0], [0.0, 0.01]]), 'Rk': np.array([[25.0]])}  # static params

        # ── Subscription buffers ───────────────────────────────────────────────
        self._gps_buf: deque = deque(maxlen=5)
        self._imu_buf: deque = deque(maxlen=20)

        # ── Subscriptions ────────────────────────────────────────────────────
        self._gps_sub = self.create_subscription(
            NavSatFix, '/gps',
            self._gps_cb, QOS,
            callback_group=self._cb_group,
        )
        self._imu_sub = self.create_subscription(
            Imu, '/imu',
            self._imu_cb, QOS,
            callback_group=self._cb_group,
        )

        # ── Publishers ────────────────────────────────────────────────────────
        self._pub_x_est_kf = self.create_publisher(
            Float64, '/x_est_kf', QOS,
        )
        self._pub_P_kf = self.create_publisher(
            Float64, '/P_kf', QOS,
        )

        self.get_logger().info("kf_estimator started")

    # ────────────────────────────────────────────────────────────────────
    # Subscription callbacks
    # ────────────────────────────────────────────────────────────────────
    # Each callback converts the incoming message to NumPy, stores it with an
    # arrival timestamp, then attempts a control step. The (time, value) tuple
    # enables the staleness check in _fresh(). _run_step() proceeds only when
    # sync_mode conditions are satisfied.

    def _gps_cb(self, msg: NavSatFix) -> None:
        arr = np.asarray(ros2py_nav_sat_fix(msg), dtype=float)  # ROS msg → NumPy
        ts = self.get_clock().now().nanoseconds * 1e-9
        self._gps_buf.append((ts, arr))
        self._run_step()

    def _imu_cb(self, msg: Imu) -> None:
        arr = np.asarray(ros2py_imu(msg), dtype=float)  # ROS msg → NumPy
        ts = self.get_clock().now().nanoseconds * 1e-9
        self._imu_buf.append((ts, arr))
        self._run_step()

    @staticmethod
    def _fresh(buf: deque, stale_after, now_ts: float):
        """Newest buffered value if its timestamp is within stale_after seconds of now_ts, else None."""
        if not buf:
            return None
        ts, val = buf[-1]
        if stale_after is not None and (now_ts - ts) > stale_after:
            return None
        return val

    # ────────────────────────────────────────────────────────────────────
    # Control step
    # ────────────────────────────────────────────────────────────────────
    # Builds kwargs from static params, dynamic params, fresh subscription
    # values, and current state, then calls DynamicalSystem.step() and
    # publishes. Skipped entirely when sync_mode conditions are not met.

    def _run_step(self) -> None:
        _now = self.get_clock().now()
        now_ts: float = _now.nanoseconds * 1e-9  # ROS clock, seconds since epoch
        tk: float = (_now - self._t0).nanoseconds * 1e-9  # seconds since node started

        # Gather fresh inputs
        gps = self._fresh(self._gps_buf, 2.0, now_ts)
        imu = self._fresh(self._imu_buf, 0.02, now_ts)

        # sync_mode='any'
        if gps is None and imu is None:
            return  # all inputs are stale — skip this tick

        kwargs: dict = {"tk": tk, **self._static_params}
        if gps is not None:
            kwargs["gps"] = gps
        if imu is not None:
            kwargs["imu"] = imu
        if self._state is not None:
            kwargs["zk"] = self._state

        result = self._system.step(**kwargs)
        if self._system.f is not None:
            self._state, yk = result  # stateful: (next_state, output)
        else:
            yk = result               # stateless: output only

        if isinstance(yk, dict) and 'x_est' in yk:
            _arr = np.asarray(yk['x_est'], dtype=float).ravel()
            msg = py2ros_float64(_arr)
            if hasattr(msg, 'header'):
                msg.header.stamp = self.get_clock().now().to_msg()
            self._pub_x_est_kf.publish(msg)
        if isinstance(yk, dict) and 'P00' in yk:
            _arr = np.asarray(yk['P00'], dtype=float).ravel()
            msg = py2ros_float64(_arr)
            if hasattr(msg, 'header'):
                msg.header.stamp = self.get_clock().now().to_msg()
            self._pub_P_kf.publish(msg)


# ──────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────

def main() -> None:
    rclpy.init()
    node = KfEstimatorNode()
    executor = SingleThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
