#!/usr/bin/env python3
"""
kalman — generated by dynamicalnodes.ROSNode.write_ROSNode_to_rclpy().

Run:
    python3 kalman_node.py
"""

# ──────────────────────────────────────────────────────────────────────
# Imports
# ──────────────────────────────────────────────────────────────────────

from collections import deque
import numpy as np

import rclpy
from rclpy.node import Node
from rclpy.executors import SingleThreadedExecutor
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.qos import QoSProfile, QoSHistoryPolicy, QoSReliabilityPolicy

from std_msgs.msg import Float64

from dynamicalnodes import DynamicalSystem
from dynamicalnodes.ros2py_py2ros import ros2py_float64, py2ros_float64


# ──────────────────────────────────────────────────────────────────────
# Functions — inlined from source
# ──────────────────────────────────────────────────────────────────────

def kf_f(zk, uk, yk, Fk, Bk, Hk, Qk, Rk):
    """Discrete Kalman predict-update. Returns updated (x_est, P)."""
    x, P = zk
    # Predict
    x_pred = Fk @ x + Bk * uk
    P_pred = Fk @ P @ Fk.T + Qk
    # Update
    yk = np.atleast_1d(yk)
    y_res = yk - Hk @ x_pred
    S = Hk @ P_pred @ Hk.T + Rk
    K = P_pred @ Hk.T @ np.linalg.inv(S)
    x_upd = x_pred + K @ y_res
    P_upd = (np.eye(len(x)) - K @ Hk) @ P_pred
    return (x_upd, P_upd)


def kf_h(zk):
    return zk[0][1]  # velocity estimate


# ──────────────────────────────────────────────────────────────────────
# QoS — tune history / depth / reliability to match your transport
# ──────────────────────────────────────────────────────────────────────

QOS = QoSProfile(
    history=QoSHistoryPolicy.KEEP_LAST,
    depth=10,
    reliability=QoSReliabilityPolicy.RELIABLE,
)


class KalmanNode(Node):

    """
    Subscribes to:
        /uk  (Float64)  →  uk  [ros2py_float64, buffer=1]
        /yk  (Float64)  →  yk  [ros2py_float64, buffer=1]
    Publishes to:
        /xhatk  (Float64)  [py2ros_float64]

    step trigger: event-driven (fires on each subscription callback)
    sync_mode='all': step only when every subscription has a fresh value.
    """

    def __init__(self) -> None:
        super().__init__("kalman")
        self._cb_group = ReentrantCallbackGroup()

        self._system = DynamicalSystem(f=kf_f, h=kf_h)
        self._state = (np.array([0.0, 0.0]), np.array([[1.0, 0.0], [0.0, 1.0]]))  # initial state
        self._t0 = self.get_clock().now()  # wall-clock reference for 'tk'

        self._static_params: dict = {'Fk': np.array([[1.0, 0.1], [0.0, 0.9966666666666667]]), 'Bk': np.array([0.0, 6.666666666666667e-05]), 'Hk': np.array([[0.0, 1.0]]), 'Qk': np.array([[0.005000000000000001, 0.0], [0.0, 0.010000000000000002]]), 'Rk': np.array([[2.0]])}  # static params

        # ── Subscription buffers ───────────────────────────────────────────────
        self._uk_buf: deque = deque(maxlen=1)
        self._yk_buf: deque = deque(maxlen=1)

        # ── Subscriptions ────────────────────────────────────────────────────
        self._uk_sub = self.create_subscription(
            Float64, '/uk',
            self._uk_cb, QOS,
            callback_group=self._cb_group,
        )
        self._yk_sub = self.create_subscription(
            Float64, '/yk',
            self._yk_cb, QOS,
            callback_group=self._cb_group,
        )

        # ── Publishers ────────────────────────────────────────────────────────
        self._pub_xhatk = self.create_publisher(
            Float64, '/xhatk', QOS,
        )

        self.get_logger().info("kalman started")

    # ────────────────────────────────────────────────────────────────────
    # Subscription callbacks
    # ────────────────────────────────────────────────────────────────────
    # Each callback converts the incoming message to NumPy, stores it with an
    # arrival timestamp, then attempts a control step. The (time, value) tuple
    # enables the staleness check in _fresh(). _run_step() proceeds only when
    # sync_mode conditions are satisfied.

    def _uk_cb(self, msg: Float64) -> None:
        arr = np.asarray(ros2py_float64(msg), dtype=float)  # ROS msg → NumPy
        ts = self.get_clock().now().nanoseconds * 1e-9
        self._uk_buf.append((ts, arr))
        self._run_step()

    def _yk_cb(self, msg: Float64) -> None:
        arr = np.asarray(ros2py_float64(msg), dtype=float)  # ROS msg → NumPy
        ts = self.get_clock().now().nanoseconds * 1e-9
        self._yk_buf.append((ts, arr))
        self._run_step()

    @staticmethod
    def _fresh(buf: deque, stale_after, now_ts: float):
        """Newest buffered value if its timestamp is within stale_after seconds of now_ts, else None."""
        if not buf:
            return None
        ts, val = buf[-1]
        if stale_after is not None and (now_ts - ts) > stale_after:
            return None
        return val

    # ────────────────────────────────────────────────────────────────────
    # Control step
    # ────────────────────────────────────────────────────────────────────
    # Builds kwargs from static params, dynamic params, fresh subscription
    # values, and current state, then calls DynamicalSystem.step() and
    # publishes. Skipped entirely when sync_mode conditions are not met.

    def _run_step(self) -> None:
        _now = self.get_clock().now()
        now_ts: float = _now.nanoseconds * 1e-9  # ROS clock, seconds since epoch
        tk: float = (_now - self._t0).nanoseconds * 1e-9  # seconds since node started

        # Gather fresh inputs
        uk = self._fresh(self._uk_buf, None, now_ts)
        yk = self._fresh(self._yk_buf, None, now_ts)

        # sync_mode='all'
        if uk is None or yk is None:
            return  # not all inputs are fresh — skip this tick

        kwargs: dict = {"tk": tk, **self._static_params}
        if uk is not None:
            kwargs["uk"] = uk
        if yk is not None:
            kwargs["yk"] = yk
        if self._state is not None:
            kwargs["zk"] = self._state

        result = self._system.step(**kwargs)
        if self._system.f is not None:
            self._state, yk = result  # stateful: (next_state, output)
        else:
            yk = result               # stateless: output only

        _arr = np.asarray(yk, dtype=float).ravel()
        msg = py2ros_float64(_arr)
        if hasattr(msg, 'header'):
            msg.header.stamp = self.get_clock().now().to_msg()
        self._pub_xhatk.publish(msg)


# ──────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────

def main() -> None:
    rclpy.init()
    node = KalmanNode()
    executor = SingleThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
