#!/usr/bin/env python3
"""
gps — generated by dynamicalnodes.ROSNode.write_ROSNode_to_rclpy().

Run:
    python3 gps_node.py
"""

# ──────────────────────────────────────────────────────────────────────
# Imports
# ──────────────────────────────────────────────────────────────────────

from collections import deque
import numpy as np

import rclpy
from rclpy.node import Node
from rclpy.executors import SingleThreadedExecutor
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.qos import QoSProfile, QoSHistoryPolicy, QoSReliabilityPolicy

from sensor_msgs.msg import NavSatFix

from dynamicalnodes import DynamicalSystem
from dynamicalnodes.ros2py_py2ros import py2ros_nav_sat_fix


# ──────────────────────────────────────────────────────────────────────
# Functions — inlined from source
# ──────────────────────────────────────────────────────────────────────

def gps_h(tk, A, omega):
    x_true = A * np.sin(omega * tk)
    return np.array([x_true, 0.0, 0.0])  # [lat=x, lon=0, alt=0]


# ──────────────────────────────────────────────────────────────────────
# QoS — tune history / depth / reliability to match your transport
# ──────────────────────────────────────────────────────────────────────

QOS = QoSProfile(
    history=QoSHistoryPolicy.KEEP_LAST,
    depth=10,
    reliability=QoSReliabilityPolicy.RELIABLE,
)


class GpsNode(Node):

    """
    Publishes to:
        /gps  (NavSatFix)  [py2ros_nav_sat_fix]

    step trigger: timer at 1 Hz
    """

    def __init__(self) -> None:
        super().__init__("gps")
        self._cb_group = ReentrantCallbackGroup()

        self._system = DynamicalSystem(h=gps_h)
        self._state = None  # initial state — set before deploying if stateful
        self._t0 = self.get_clock().now()  # wall-clock reference for 'tk'

        self._static_params: dict = {'A': 50.0, 'omega': 0.10471975511965977}  # static params

        # ── Publishers ────────────────────────────────────────────────────────
        self._pub_gps = self.create_publisher(
            NavSatFix, '/gps', QOS,
        )

        # ── Timer ────────────────────────────────────────────────────────────
        self._timer = self.create_timer(
            1.0,  # 1 Hz
            self._run_step,
            callback_group=self._cb_group,
        )

        self.get_logger().info("gps started")

    @staticmethod
    def _fresh(buf: deque, stale_after, now_ts: float):
        """Newest buffered value if its timestamp is within stale_after seconds of now_ts, else None."""
        if not buf:
            return None
        ts, val = buf[-1]
        if stale_after is not None and (now_ts - ts) > stale_after:
            return None
        return val

    # ────────────────────────────────────────────────────────────────────
    # Control step
    # ────────────────────────────────────────────────────────────────────
    # Builds kwargs from static params, dynamic params, fresh subscription
    # values, and current state, then calls DynamicalSystem.step() and
    # publishes. Skipped entirely when sync_mode conditions are not met.

    def _run_step(self) -> None:
        _now = self.get_clock().now()
        now_ts: float = _now.nanoseconds * 1e-9  # ROS clock, seconds since epoch
        tk: float = (_now - self._t0).nanoseconds * 1e-9  # seconds since node started

        kwargs: dict = {"tk": tk, **self._static_params}

        result = self._system.step(**kwargs)
        if self._system.f is not None:
            self._state, yk = result  # stateful: (next_state, output)
        else:
            yk = result               # stateless: output only

        _arr = np.asarray(yk, dtype=float).ravel()
        _arr = _arr + np.random.normal(0.0, 5.0, _arr.shape)  # noise std=5.0
        msg = py2ros_nav_sat_fix(_arr)
        if hasattr(msg, 'header'):
            msg.header.stamp = self.get_clock().now().to_msg()
        self._pub_gps.publish(msg)


# ──────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────

def main() -> None:
    rclpy.init()
    node = GpsNode()
    executor = SingleThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
